#!/usr/bin/env python
"""Rebuild volume_vertices robustly: enumerate true vertices (2-close interior check),
then compute the polytope volume via ConvexHull with options tolerant to non-simplicial
polytopes (Qt), with aggressive dedup to remove near-duplicate/near-coplanar float noise,
and NO QJ (which corrupts volume). Fall back to a scaled/tolerance sweep.
Also prints per-vertex count and volume for calibration on a heavy k=5 rep.
"""
import numpy as np, itertools, scipy.spatial

def volume_vertices_robust(N):
    n,m=N.shape
    if m==0: return 1.0
    A_rows=N; verts=[]; best=[]
    for idxs in itertools.combinations(range(n), m):
        Mtx=np.array([A_rows[j] for j in idxs])
        if abs(np.linalg.det(Mtx))<1e-8: continue
        for signs in itertools.product([1,-1],repeat=m):
            rhs=0.5*np.array(signs)
            try: t=np.linalg.solve(Mtx,rhs)
            except np.linalg.LinAlgError: continue
            # tighter inside check
            if np.all(np.abs(N@t)<=0.5+1e-7):
                verts.append(t)
    if not verts: return None
    pts=np.array(verts)
    # dedupe with tolerance via rounding to 5 decimal
    pts=np.unique(np.round(pts,5),axis=0)
    if m==1:
        xs=sorted(p[0] for p in pts)
        return xs[-1]-xs[0]
    if len(pts)<m+1: return 0.0
    try:
        hull=scipy.spatial.ConvexHull(pts, qhull_options="Qt")
        return hull.volume
    except Exception as e:
        # retry with Q12 (allow wide merge) as last resort
        try:
            hull=scipy.spatial.ConvexHull(pts, qhull_options="Qt Q12")
            return hull.volume
        except Exception as e2:
            return None

# quick self-test on a simple centrally-symmetric box-like example
if __name__=="__main__":
    # m=2 box |t1|<1/2,|t2|<1/2 -> N=[[1,0],[0,1]]
    N=np.eye(2)
    print("box2x2 vol (expect 1):", volume_vertices_robust(N))
    # m=2 diamond generated by N=[[-1,1,1],[1,-1,1]] ? bad example; skip
