#!/usr/bin/env python3
"""Generate Lean 4 source files/defs for the exact-rational kernel table.

Reads the JSON emitted by emit_kernel_table.py and writes a Lean module with
`kernelTable : List (Int × Nat)` storing exact (numerator, denominator) pairs.
The table is split into small chunk defs (default 256 entries per def) and
concatenated, to avoid Lean's recursion-depth limit on a single giant list.

Usage:
  py -3.10 emit_kernel_table_lean.py --json PATH --out PATH --module T2Data
"""
from __future__ import annotations

import argparse, json

CHUNK = 256

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--json', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--module', default='T2Data')
    args = ap.parse_args()

    with open(args.json, 'r', encoding='utf-8') as f:
        data = json.load(f)
    entries = data['entries']

    lines = []
    lines.append("/- Auto-generated by emit_kernel_table_lean.py. Do not edit. -/")
    lines.append("set_option maxHeartbeats 0")
    lines.append("set_option maxRecDepth 100000")
    lines.append("")
    lines.append(f"namespace {args.module}")
    lines.append("")

    chunk_defs = []
    for ci in range(0, len(entries), CHUNK):
        chunk = entries[ci:ci+CHUNK]
        name = f"kernelTableChunk{ci // CHUNK}"
        chunk_defs.append(name)
        lines.append(f"def {name} : List (Int × Nat) := [")
        for i in range(0, len(chunk), 8):
            pairs = [f"({num}, {den})" for num, den in chunk[i:i+8]]
            lines.append("  " + ", ".join(pairs) + ",")
        lines.append("]")
        lines.append("")

    combine = " ++ ".join(chunk_defs)
    lines.append(f"def kernelTable : List (Int × Nat) := {combine}")
    lines.append("")
    lines.append(f"def kernelTableEntries : Nat := {len(entries)}")
    lines.append("")
    lines.append(f"end {args.module}")
    lines.append("")

    text = "\n".join(lines)
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f"wrote {args.out}: {len(entries)} entries, {len(chunk_defs)} chunks, {len(text)} chars")

if __name__ == '__main__':
    main()
