#!/usr/bin/env python3
"""Generate a Lean 4 source file containing the exact-rational kernel table.

Reads the JSON emitted by emit_kernel_table.py and writes a Lean module with
`kernelTable : List ℚ`, one rational per cell. This is the T2 reflection data
artifact: a later Lean checker can use it as the exact lower-bound table.

Usage:
  py -3.10 emit_kernel_table_lean.py --json PATH --out PATH --module T2Data
"""
from __future__ import annotations

import argparse, json

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--json', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--module', default='T2Data')
    args = ap.parse_args()

    with open(args.json, 'r', encoding='utf-8') as f:
        data = json.load(f)

    entries = data['entries']
    lines = []
    lines.append(f"/- Auto-generated by emit_kernel_table_lean.py. Do not edit. -/")
    lines.append("")
    lines.append(f"namespace {args.module}")
    lines.append("")
    lines.append("def kernelTable : List ℚ := [")
    # Emit in chunks to keep lines readable.
    chunk = 8
    for i in range(0, len(entries), chunk):
        nums = []
        for num, den in entries[i:i+chunk]:
            nums.append(f"(({num} : ℚ) / ({den} : ℚ))")
        lines.append("  " + ", ".join(nums) + ",")
    lines.append("]")
    lines.append("")
    lines.append(f"def kernelTableEntries : Nat := kernelTable.length")
    lines.append("")
    lines.append("end " + args.module)
    lines.append("")

    text = "\n".join(lines)
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f"wrote {args.out}: {len(entries)} entries, {len(text)} chars")

if __name__ == '__main__':
    main()
